services:
- type: web
  buildCommand: pip install -r requirements.txt && python manage.py migrate
  startCommand: python manage.py runserver
  env: 'python'
  plan: starter
  name: Data-Djanto
  envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: core.settings

staticSites:
- buildCommand: python manage.py collectstatic --noinput
  publicDir: staticfiles
  name: Data-Djanto-statics

routes:
- type: rewrite
  source: /static/(.*)
  #destination: https://Data-Djanto-statics.onrender.com/$1